server:
  servlet:
    encoding.force: true  # intelliJ 한글깨짐 방지

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testdb1
    username: sa
    password:

  profiles:
    include: oauth